### ISSUE TITLE
Broken links for VM

### ISSUE THREAD

**Issue by steakunderscore** [railsbridge-montreal/docs#7]
Ces liens ne marchent pas:
- http://download.virtualbox.org/virtualbox/4.3.10/VirtualBox-4.3.10-93012-Win.exe
- https://dl.bintray.com/mitchellh/vagrant/vagrant_1.5.1.msi
- https://www.dropbox.com/s/n0hio7qcbvipbyd/railsbridgevm-2014-04-rc2.box

Merci de les vérifier.

**Comment by benichu** [comment]
@steakunderscore I think we would have to forego trying to use a VM as an installation method.
too risky. what do you think?

**Comment by steakunderscore** [comment]
I found this: http://docs.railsbridgeboston.org/downloads/

So I'm just going to link to their page for now.

**Comment by sophiedeziel** [comment]
:+1: !!
